spring.application.name=smartorder-platform
server.port=8080
spring.couchbase.connection-string=127.0.0.1
spring.couchbase.username=Administrator
spring.couchbase.password=password123
spring.data.couchbase.bucket-name=smartorder-core
#logging.level.com.couchbase=WARN
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.couchbase.CouchbaseAutoConfiguration,org.springframework.boot.autoconfigure.data.couchbase.CouchbaseDataAutoConfiguration,org.springframework.boot.autoconfigure.data.couchbase.CouchbaseRepositoriesAutoConfiguration
logging.level.com.couchbase=ERROR
logging.level.com.couchbase.io=OFF
logging.level.com.couchbase.endpoint=OFF