# Prod profile - production settings
logging.level.com.smartorder=ERROR
spring.couchbase.connection-string=${CB_CONNECTION}
spring.couchbase.username=${CB_USERNAME}
spring.couchbase.password=${CB_PASSWORD}