spring.profiles.active=dev
spring.application.name=smartorder-platform
server.port=8080
spring.couchbase.connection-string=127.0.0.1
spring.couchbase.username=Administrator
spring.couchbase.password=Admin@1234
spring.data.couchbase.bucket-name=smartorder-core
logging.level.com.couchbase=ERROR
logging.level.com.couchbase.io=OFF
logging.level.com.couchbase.endpoint=OFF
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.couchbase.CouchbaseAutoConfiguration,org.springframework.boot.autoconfigure.data.couchbase.CouchbaseDataAutoConfiguration,org.springframework.boot.autoconfigure.data.couchbase.CouchbaseRepositoriesAutoConfiguration

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=smartorder-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka Topics
smartorder.kafka.topic.order=order.events
smartorder.kafka.topic.payment=payment.events
smartorder.kafka.topic.feed=feed.updates
smartorder.kafka.topic.alerts=era.alerts
smartorder.kafka.topic.notifications=notifications
smartorder.kafka.topic.audit=audit.logs