spring.application.name=smartorder-platform
server.port=8080
spring.couchbase.connection-string=127.0.0.1
spring.couchbase.username=Administrator
spring.couchbase.password=password123
spring.data.couchbase.bucket-name=smartorder-core
logging.level.com.couchbase=WARN